-- Create recipes table if it doesn't exist
CREATE TABLE IF NOT EXISTS recipes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    ingredients TEXT NOT NULL,
    instructions TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample recipes
INSERT INTO recipes (name, ingredients, instructions) VALUES
('Classic Spaghetti Bolognese', '500g ground beef, 1 onion, 2 cloves garlic, 400g canned tomatoes, 2 tbsp tomato paste, 1 tsp dried oregano, 400g spaghetti, salt and pepper to taste', '1. Brown the beef in a large pan\n2. Add chopped onion and garlic, cook until soft\n3. Add tomatoes, tomato paste, and oregano\n4. Simmer for 20 minutes\n5. Cook spaghetti according to package instructions\n6. Serve sauce over spaghetti'),
('Chicken Stir Fry', '2 chicken breasts, 2 bell peppers, 1 onion, 2 cups broccoli, 3 tbsp soy sauce, 2 tbsp vegetable oil, 2 cloves garlic, 1 tsp ginger', '1. Cut chicken into bite-sized pieces\n2. Heat oil in a wok or large pan\n3. Stir-fry chicken until cooked through\n4. Add vegetables and stir-fry for 5 minutes\n5. Add soy sauce, garlic, and ginger\n6. Cook for 2 more minutes'),
('Vegetable Soup', '2 carrots, 2 celery stalks, 1 onion, 2 potatoes, 1 can diced tomatoes, 4 cups vegetable broth, 2 cloves garlic, 1 tsp thyme, salt and pepper to taste', '1. Chop all vegetables\n2. Heat oil in a large pot\n3. Sauté onion and garlic\n4. Add remaining vegetables and cook for 5 minutes\n5. Add broth and tomatoes\n6. Simmer for 20 minutes until vegetables are tender'),
('Chocolate Chip Cookies', '2 1/4 cups flour, 1 cup butter, 3/4 cup sugar, 3/4 cup brown sugar, 2 eggs, 1 tsp vanilla, 1 tsp baking soda, 2 cups chocolate chips', '1. Cream butter and sugars\n2. Add eggs and vanilla\n3. Mix in dry ingredients\n4. Fold in chocolate chips\n5. Drop by spoonfuls onto baking sheet\n6. Bake at 350°F for 10-12 minutes'),
('Greek Salad', '1 cucumber, 4 tomatoes, 1 red onion, 200g feta cheese, 1/2 cup Kalamata olives, 2 tbsp olive oil, 1 tbsp red wine vinegar, 1 tsp dried oregano, salt and pepper to taste', '1. Chop cucumber, tomatoes, and onion into chunks\n2. Combine vegetables in a large bowl\n3. Add olives and crumbled feta cheese\n4. Whisk together olive oil, vinegar, and oregano\n5. Pour dressing over salad and toss gently\n6. Season with salt and pepper'),
('Quinoa Bowl', '1 cup quinoa, 2 cups vegetable broth, 1 avocado, 1 cup cherry tomatoes, 1/2 cup corn, 1/4 cup black beans, 1 lime, 2 tbsp olive oil, fresh cilantro, salt and pepper to taste', '1. Rinse quinoa and cook in vegetable broth\n2. Chop avocado and tomatoes\n3. Combine cooked quinoa with vegetables\n4. Add corn and black beans\n5. Squeeze lime juice and drizzle olive oil\n6. Garnish with cilantro and season to taste'),
('Pasta Primavera', '400g pasta, 2 cups mixed vegetables (broccoli, carrots, bell peppers), 2 cloves garlic, 1/4 cup olive oil, 1/4 cup parmesan cheese, 1/4 cup heavy cream, fresh basil, salt and pepper to taste', '1. Cook pasta according to package instructions\n2. Sauté vegetables and garlic in olive oil\n3. Add cooked pasta to vegetables\n4. Stir in cream and parmesan cheese\n5. Cook for 2 minutes until sauce thickens\n6. Garnish with fresh basil'),
('Smoothie Bowl', '2 frozen bananas, 1 cup mixed berries, 1 cup almond milk, 2 tbsp honey, 1/4 cup granola, 1 tbsp chia seeds, fresh fruit for topping', '1. Blend frozen bananas, berries, and almond milk\n2. Pour into a bowl\n3. Top with granola and chia seeds\n4. Arrange fresh fruit on top\n5. Drizzle with honey\n6. Serve immediately'),
('Taco Salad', '500g ground beef, 1 packet taco seasoning, 1 head lettuce, 1 tomato, 1 avocado, 1/2 cup corn, 1/2 cup black beans, 1 cup tortilla chips, 1/4 cup sour cream, 1/4 cup salsa', '1. Cook beef with taco seasoning\n2. Chop lettuce, tomato, and avocado\n3. Combine vegetables in a large bowl\n4. Add cooked beef, corn, and beans\n5. Top with crushed tortilla chips\n6. Serve with sour cream and salsa'),
('Chicken Curry', '4 chicken thighs, 1 onion, 2 cloves garlic, 1 can coconut milk, 2 tbsp curry paste, 1 tbsp fish sauce, 1 tbsp brown sugar, fresh cilantro, lime wedges', '1. Cut chicken into bite-sized pieces\n2. Sauté onion and garlic until soft\n3. Add curry paste and cook for 1 minute\n4. Add chicken and cook until browned\n5. Pour in coconut milk and simmer for 20 minutes\n6. Season with fish sauce and brown sugar\n7. Garnish with cilantro and serve with lime wedges'),
('Vegetable Lasagna', '12 lasagna noodles, 2 cups marinara sauce, 2 cups ricotta cheese, 2 cups mozzarella, 2 cups mixed vegetables (zucchini, spinach, mushrooms), 2 cloves garlic, 1/4 cup parmesan cheese', '1. Cook lasagna noodles according to package\n2. Sauté vegetables and garlic\n3. Layer noodles, sauce, vegetables, and cheeses\n4. Repeat layers until all ingredients are used\n5. Top with parmesan cheese\n6. Bake at 375°F for 30 minutes'),
('Avocado Toast', '4 slices bread, 2 avocados, 2 eggs, 1 lemon, red pepper flakes, salt and pepper to taste, microgreens for garnish', '1. Toast bread slices\n2. Mash avocados with lemon juice\n3. Fry or poach eggs\n4. Spread avocado on toast\n5. Top with eggs\n6. Season with salt, pepper, and red pepper flakes\n7. Garnish with microgreens'),
('Shrimp Scampi', '500g shrimp, 400g linguine, 4 cloves garlic, 1/4 cup butter, 1/4 cup olive oil, 1/4 cup white wine, 1 lemon, fresh parsley, red pepper flakes', '1. Cook linguine according to package\n2. Sauté garlic in butter and oil\n3. Add shrimp and cook until pink\n4. Pour in white wine and lemon juice\n5. Toss with cooked pasta\n6. Garnish with parsley and red pepper flakes'),
('Fruit Smoothie', '1 banana, 1 cup mixed berries, 1 cup yogurt, 1 cup orange juice, 2 tbsp honey, ice cubes', '1. Add all ingredients to blender\n2. Blend until smooth\n3. Add more ice if needed\n4. Pour into glasses\n5. Serve immediately'),
('Caprese Salad', '4 tomatoes, 200g fresh mozzarella, fresh basil leaves, 2 tbsp balsamic glaze, 2 tbsp olive oil, salt and pepper to taste', '1. Slice tomatoes and mozzarella\n2. Arrange on a plate alternating slices\n3. Tuck basil leaves between slices\n4. Drizzle with balsamic glaze and olive oil\n5. Season with salt and pepper\n6. Serve immediately'); 